apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fs-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: fs-api
            port:
              number: 8000
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: fs-frontend
            port:
              number: 80