kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
      - containerPort: 30010
        hostPort: 8085
      - containerPort: 30090
        hostPort: 3000
      - containerPort: 30081
        hostPort: 8081
        
  - role: worker
  - role: worker