grafana:
  adminUser: admin           # gebruikersnaam instellen  als admin
  adminPassword: admin       # Wachtwoord instellen als admin
  service:
    type: NodePort           # Grafana bereikbaar maken via een NodePort-service
    nodePort: 30090          # poort 30090 als nodeport instellen
